<?php $this->include_view("header", array("title" => $this->translate("article.edit"))); ?>

   <div class="container theme-showcase" role="main">
      <div class="jumbotron" style="margin-top: 80px;">
       	<?php 
       		if ($this->form->get("id") > 0)
       			$action = $this->link("article_update", array("id" => $this->form->get("id")));
       		else
       			$action = $this->link("article_post");
       	?>
		<form action="<?php echo $action ?>" class="form-horizontal" method="POST">
		<?php 
			$form = $this->form;
			if (count($form->errors) != 0) { ?>
				<div class="row">
					<div class="col-sm-push-2 col-sm-10">
						<p class="bg-danger" style="padding: 0 10px;">
							<?php 
								foreach($form->getFields() as $field) {
									if ($field->error) {
										echo $this->translate($form->getName() . "." . $field->name . "." . $field->error);
										echo "<br>";
									}
								}
							?>
						</p>
					</div>
				</div>
		<?php }
			$this->include_view("text_field", array(
				"name" => "form[title]", 
				"value" => $form->get("title"), 
				"placeholder" => $this->translate("article.form.title"),
				));
			$this->include_view("text_field", array(
				"name" => "form[promo_text]", 
				"value" => $form->get("promo_text"), 
				"placeholder" => $this->translate("article.form.promo_text"),
				));
			$this->include_view("textarea_field", array(
				"name" => "form[text]", 
				"value" => $form->get("text"), 
				"placeholder" => $this->translate("article.form.text"),
				));
		?>
		  <div class="form-group">
		    <div class="col-sm-offset-2 col-sm-10">
		      <button type="submit" class="btn btn-default"><?php echo $this->translate("article.form.save"); ?></button>
		    </div>
		  </div>
		</form>

      </div>
    </div>

<?php $this->include_view("footer"); ?>
