<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>OOPS...</title>

    <link href="<?php $this->echoAsset("css/bootstrap.min.css"); ?>" rel="stylesheet">
    <link href="<?php $this->echoAsset("css/cover.css"); ?>" rel="stylesheet">

  </head>
  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="inner cover">
            <h1 class="cover-heading"><?php echo $this->translate("error"); ?></h1>
            <p class="lead"><?php echo $this->translate("errors." . $this->message); ?></p>
            <p class="lead">
              <a href="<?php $this->echoLink("home"); ?>" class="btn btn-lg btn-default"><?php echo $this->translate("error_home"); ?></a>
            </p>
          </div>

        </div>

      </div>

    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="<?php $this->echoAsset("js/bootstrap.min.js"); ?>"></script>

</body>
</html>
