	<div class="container">
		<footer>
			<p class="pull-right"><a href="#"><?php echo $this->translate("misc.back_to_top"); ?></a></p>
			<p>&copy; <?php echo $this->translate("company"); ?> &middot;</p>
		</footer>
	</div>

 	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
 	<script src="<?php $this->echoAsset("js/bootstrap.min.js"); ?>"></script>
 	<?php 
		if ($this->scripts) {
			echo $this->scripts;
		} 
 	?>
	</body>
	</html>
