<?php $this->include_view("header", array("section" => "home")); ?>

<div id="carousel" class="carousel slide" data-ride="carousel">

	<ol class="carousel-indicators">
		<li data-target="#carousel1" data-slide-to="0" class="active"></li>
		<li data-target="#carousel2" data-slide-to="1"></li>
		<li data-target="#carousel3" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner" role="listbox">
		<div class="item active">
			<img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
			<div class="container">
				<div class="carousel-caption">
					<h1><?php echo $this->translate("slider.caption.first"); ?></h1>
					<p><?php echo $this->translate("slider.content.first"); ?></p>
					<p><a class="btn btn-lg btn-primary" href="<?php $this->echoLink("gallery_show"); ?>" role="button"><?php echo $this->translate("slider.button.first"); ?></a></p>
				</div>
			</div>
		</div>
		<div class="item">
			<img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
			<div class="container">
				<div class="carousel-caption">
					<h1><?php echo $this->translate("slider.caption.second"); ?></h1>
					<p><?php echo $this->translate("slider.content.second"); ?></p>
					<p><a class="btn btn-lg btn-primary" href="<?php $this->echoLink("news"); ?>" role="button"><?php echo $this->translate("slider.button.second"); ?></a></p>
				</div>
			</div>
		</div>
		<div class="item">
			<img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
			<div class="container">
				<div class="carousel-caption">
					<h1><?php echo $this->translate("slider.caption.third"); ?></h1>
					<p><?php echo $this->translate("slider.content.third"); ?></p>
					<p><a class="btn btn-lg btn-primary" href="<?php $this->echoLink("article_add"); ?>" role="button"><?php echo $this->translate("slider.button.third"); ?></a></p>
				</div>
			</div>
		</div>
	</div>
	<a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="right carousel-control" href="#carousel" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>

<div class="container marketing">

	<div class="row featurette">
		<div class="col-md-7">
			<h2 class="featurette-heading"><?php echo $this->translate("promo.caption.first"); ?></span></h2>
			<p class="lead"><?php echo $this->translate("promo.content.first"); ?></p>
		</div>
		<div class="col-md-5">
			<img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
		</div>
	</div>

	<hr class="featurette-divider">

	<div class="row featurette">
		<div class="col-md-7 col-md-push-5">
			<h2 class="featurette-heading"><?php echo $this->translate("promo.caption.second"); ?></span></h2>
			<p class="lead"><?php echo $this->translate("promo.content.second"); ?></p>
		</div>
		<div class="col-md-5 col-md-pull-7">
			<img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
		</div>
	</div>

	<hr class="featurette-divider">

	<div class="row featurette">
		<div class="col-md-7">
			<h2 class="featurette-heading"><?php echo $this->translate("promo.caption.third"); ?></span></h2>
			<p class="lead"><?php echo $this->translate("promo.content.third"); ?></p>
		</div>
		<div class="col-md-5">
			<img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
		</div>
	</div>

	<hr class="featurette-divider">
</div>

<?php 
	$scripts = "<script src=\"" . $this->asset("js/holder.js") . "\"></script>";
	$this->include_view("footer", array("scripts" => $scripts)); 
?>